version: "3.7"

services:
  backups:
    build:
      context: ../
    entrypoint: /app/docker/entrypoint.sh
    command: bash -c "bundle exec ./backups.rb"
    container_name: "backups"
    volumes:
      - ../:/app
      - backups_bundle:/bundle
    env_file: ../.env
    environment:
      BUNDLE_PATH: /bundle
      BUNDLE_SILENCE_ROOT_WARNING: 1

  backups_bundle:
    image: busybox
    container_name: "backups_bundle"
    volumes:
      - backups_bundle:/bundle

volumes:
  backups_bundle:
